// <auto-generated />
using MVC_App.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_App.Migrations
{
    [DbContext(typeof(MVCApp))]
    [Migration("20250114173039_UpdateTableName")]
    partial class UpdateTableName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BillsCall", b =>
                {
                    b.Property<int>("BillId")
                        .HasColumnType("int")
                        .HasColumnName("Bill_ID");

                    b.Property<int>("CallId")
                        .HasColumnType("int")
                        .HasColumnName("Call_ID");

                    b.HasKey("BillId", "CallId")
                        .HasName("PK__BillsCal__6EF0120DAF4D5708");

                    b.HasIndex("CallId");

                    b.ToTable("BillsCalls", (string)null);
                });

            modelBuilder.Entity("MVC_App.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Admin_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_id");

                    b.HasKey("AdminId")
                        .HasName("PK__Admin__4A3006F7F49AC148");

                    b.HasIndex("UserId");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("MVC_App.Models.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Bill_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillId"));

                    b.Property<decimal?>("Costs")
                        .HasColumnType("decimal(7, 2)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("BillId")
                        .HasName("PK__Bills__CF6E7D4369376886");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("MVC_App.Models.Call", b =>
                {
                    b.Property<int>("CallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Call_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CallId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CallId")
                        .HasName("PK__Calls__19E6F4EBB48E76CB");

                    b.ToTable("Calls");
                });

            modelBuilder.Entity("MVC_App.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Client_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Afm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AFM");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("phoneNumber");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_id");

                    b.HasKey("ClientId")
                        .HasName("PK__Clients__75A5D7182B365D98");

                    b.HasIndex("UserId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("MVC_App.Models.Phone", b =>
                {
                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ProgrammName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PhoneNumber")
                        .HasName("PK__Phones__85FB4E395D793215");

                    b.HasIndex("ProgrammName");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("MVC_App.Models.Programm", b =>
                {
                    b.Property<string>("ProgrammName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Benfits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Charge")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("ProgrammName")
                        .HasName("PK__Programs__4F925711BFB93566");

                    b.ToTable("Programms");
                });

            modelBuilder.Entity("MVC_App.Models.Seller", b =>
                {
                    b.Property<int>("SellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Seller_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SellerId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_id");

                    b.HasKey("SellerId")
                        .HasName("PK__Sellers__016148B1D10B493F");

                    b.HasIndex("UserId");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("MVC_App.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("User_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("First_Name");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Last_Name");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__206A9DF89E4F90D1");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BillsCall", b =>
                {
                    b.HasOne("MVC_App.Models.Bill", null)
                        .WithMany()
                        .HasForeignKey("BillId")
                        .IsRequired()
                        .HasConstraintName("FK__BillsCall__Bill___4BAC3F29");

                    b.HasOne("MVC_App.Models.Call", null)
                        .WithMany()
                        .HasForeignKey("CallId")
                        .IsRequired()
                        .HasConstraintName("FK__BillsCall__Call___4CA06362");
                });

            modelBuilder.Entity("MVC_App.Models.Admin", b =>
                {
                    b.HasOne("MVC_App.Models.User", "User")
                        .WithMany("Admins")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Admin__User_id__3F466844");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MVC_App.Models.Bill", b =>
                {
                    b.HasOne("MVC_App.Models.Phone", "PhoneNumberNavigation")
                        .WithMany("Bills")
                        .HasForeignKey("PhoneNumber")
                        .IsRequired()
                        .HasConstraintName("FK__Bills__PhoneNumb__46E78A0C");

                    b.Navigation("PhoneNumberNavigation");
                });

            modelBuilder.Entity("MVC_App.Models.Client", b =>
                {
                    b.HasOne("MVC_App.Models.User", "User")
                        .WithMany("Clients")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Clients__User_id__3C69FB99");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MVC_App.Models.Phone", b =>
                {
                    b.HasOne("MVC_App.Models.Programm", "ProgrammNameNavigation")
                        .WithMany("Phones")
                        .HasForeignKey("ProgrammName")
                        .IsRequired()
                        .HasConstraintName("FK__Phones__ProgramN__440B1D61");

                    b.Navigation("ProgrammNameNavigation");
                });

            modelBuilder.Entity("MVC_App.Models.Seller", b =>
                {
                    b.HasOne("MVC_App.Models.User", "User")
                        .WithMany("Sellers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Sellers__User_id__398D8EEE");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MVC_App.Models.Phone", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("MVC_App.Models.Programm", b =>
                {
                    b.Navigation("Phones");
                });

            modelBuilder.Entity("MVC_App.Models.User", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Clients");

                    b.Navigation("Sellers");
                });
#pragma warning restore 612, 618
        }
    }
}
